# Generated by Django 5.0.4 on 2024-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='id в телеграме'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default=None, max_length=250, verbose_name='ник в телеграме'),
        ),
    ]
