# Generated by Django 5.0.4 on 2024-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_user_id_user_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(max_length=250, verbose_name='ник в телеграме'),
        ),
    ]
