# Generated by Django 5.0.4 on 2024-04-12 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='действие')),
                ('time', models.TimeField(verbose_name='время')),
                ('place', models.CharField(max_length=250, verbose_name='место')),
                ('frequency', models.CharField(choices=[('1', 'ежедневно'), ('2', 'раз в два дня'), ('3', 'раз в три дня'), ('4', 'раз в четыре дня'), ('5', 'раз в пять дней'), ('6', 'раз в шесть дней'), ('7', 'раз в семь дней')], default='1', max_length=20, verbose_name='периодичность')),
                ('duration', models.TimeField(verbose_name='время на выполнение')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('connected_habit_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='связанная привычка')),
                ('award', models.PositiveIntegerField(blank=True, null=True, verbose_name='вознаграждение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
