# Generated by Django 5.0.4 on 2024-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_planhabit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_execution',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='последнее выполнение'),
        ),
    ]
